# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool: 'Default'

variables:
  gisHelperImageName: 'Amz.GisHelper.App'

steps:
- task: Docker@2
  displayName: Login to docker registry
  inputs:
    command: login
    containerRegistry: nexus-docker.megapolis-it.ru

- task: Docker@2
  displayName: Build an $(gisHelperImageName) image
  inputs:
    repository: $(System.TeamProject)/$(gisHelperImageName)
    command: buildAndPush
    buildContext: '$(Build.Repository.LocalPath)/src'
    dockerfile: src/$(gisHelperImageName)/Dockerfile
    tags: |
      $(Build.SourceBranchName)
      $(Build.BuildId)
      $(Build.SourceVersion)
